title: "Dr. Sebastian Domsch | Data Scientist & Physicist | Expert for Marketing Analytics | Research Enthusiast"
author: "Dr. Sebastian Domsch"
description: "Dr. Sebastian Domsch"
permalink: /title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout
show_social: true # show site description and social links in the footer
show_excerpts: false        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu xxx
navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "cv.md", title: "Resumee", sidebaricon: home}
  - {file: "projects.md", title: "Projects", sidebaricon: home}
  - {file: "publications.md", title: "Publications", sidebaricon: home}
  - {file: "contact.md", title: "Contact", sidebaricon: home}
  #- {file: "imprint.md", title: "Imprint", sidebaricon: home}
  #- {file: "privacy.md", title: "Privacy", sidebaricon: home}
  #- {file: "myblog.md", title: "Blog", sidebaricon: home}
 
external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: XING, icon: xing, url: "https://www.xing.com/profile/rernatSebastian_Domsch"}
  - {title: LinkedIn, icon: linkedin, url: "https://www.linkedin.com/in/dr-sebastian-domsch-342a3642"}
  - {title: Youtube, icon: youtube, url: "https://www.youtube.com"}
  - {title: Github, icon: github, url: "https://github.com/Sebastian1981"}
  - {title: Dockerhub, icon: docker, url: "https://hub.docker.com/u/63531981"}
  - {title: Researchgate, icon: researchgate, url: "https://www.researchgate.net/profile/Sebastian-Domsch"}
  - {title: Mail, icon: envelope, url: "mailto: SDomsch@gmail.com"}
  - {title: "Imprint", sidebaricon: home, file: "imprint.md",  }
  - {title: "Privacy", sidebaricon: home, file: "privacy.md"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed

theme: jekyll-theme-tactile
