title: "Dr. rer. nat. Sebastian Domsch"
author: "Dr. rer. nat. Sebastian Domsch"
description: "Data Analytics"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout
show_social: true # show site description and social links in the footer
show_excerpts: false        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu xxx

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "cv.md", title: "CV", sidebaricon: home}
  - {file: "publications.md", title: "Publications", sidebaricon: home}
  - {file: "myprojects.md", title: "Github Projects"}
 

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: XING, icon: xing, url: "https://www.xing.com/profile/rernatSebastian_Domsch"}
  - {title: LinkedIn, icon: linkedin, url: "https://www.linkedin.com/in/dr-sebastian-domsch-342a3642"}
  #- {title: Utube, icon: YouTube, url: "https://github.com/Sebastian1981"}
  - {title: Github, icon: github, url: "https://github.com/Sebastian1981"}
  - {title: Researchgate, icon: Researchgate, url: "https://www.researchgate.net/profile/Sebastian-Domsch"}
  - {title: Mail, icon: envelope, url: "mailto:sebastian.domsch@googlemail.com"}



comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed

theme: jekyll-theme-tactile
